# Your first steps with Julia

## Przemysław Szufel

In [1]:
# Ctrl + ENTER
versioninfo()

Julia Version 1.8.2
Commit 36034abf26 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 4 × Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, haswell)
  Threads: 1 on 4 virtual cores


In [2]:
pwd()

"e:\\Repozytoria\\MIT_18.S097_Introduction-to-Julia-for-Data-Science\\Day-1a_Your-first-steps-with-Julia"

#shows the status of Julia Packages:

In [9]:
]st

Project MIT_18S097 v0.1.0
Status `E:\Repozytoria\MIT_18.S097_Introduction-to-Julia-for-Data-Science\Project.toml`
  [1520ce14] AbstractTrees v0.4.3
  [fbb218c0] BSON v0.3.6
  [6e4b80f9] BenchmarkTools v1.3.2
→ [024491cd] BetaML v0.9.5
→ [336ed68f] CSV v0.10.9
  [49dc2e85] Calculus v0.5.1
  [324d7699] CategoricalArrays v0.10.7
  [8f4d0f93] Conda v1.7.0
→ [d58978e5] Dagger v0.16.3
→ [a93c6f00] DataFrames v1.4.4
  [1313f7d8] DataFramesMeta v0.12.0
 ⌃ [31c24e10] Distributions v0.25.79
→⌃ [f6006082] EvoTrees v0.14.6
→ [587475ba] Flux v0.13.11
  [da1fdf0e] FreqTables v0.4.5
  [38e38edf] GLM v1.8.1
→ [c43c736e] Genie v5.13.0
  [86223c79] Graphs v1.7.4
→⌃ [cd3eb016] HTTP v1.6.3
→ [87dc4568] HiGHS v1.4.1
→ [7073ff75] IJulia v1.24.0
  [b6b21f68] Ipopt v1.1.0
  [682c06a0] JSON v0.21.3
  [0f8b85d8] JSON3 v1.12.0
→ [4076af6c] JuMP v1.6.0
→ [add582a8] MLJ v0.19.1
→ [c6f25543] MLJDecisionTreeInterface v0.3.0
→ [f6097e2c] MultiJuMP v0.6.1
→ [2dcacdae] ParallelDataTransfer v0.5.0
  [d96e819e] Parameter

In [10]:
;ls -la

LoadError: IOError: could not spawn `ls -la`: no such file or directory (ENOENT)

In [11]:
function f(x,y) 
    x+y
end 

f(x,y) = x+y

f (generic function with 1 method)

In [12]:
f(5,12)

17

In [13]:
@code_lowered f(5,6) #first stage of compilation

CodeInfo(
1 ─ %1 = x + y
└──      return %1
)

In [14]:
@code_typed f(4,5) #second

CodeInfo(
1 ─ %1 = Base.add_int(x, y)::Int64
└──      return %1
) => Int64

In [16]:
@code_llvm f(5,6) # next - code translated for low level virtual machine

;  @ In[11]:5 within `f`
; Function Attrs: uwtable
define i64 @julia_f_2479(i64 signext %0, i64 signext %1) #0 {
top:
; ┌ @ int.jl:87 within `+`
   %2 = add i64 %1, %0
; └
  ret i64 %2
}


In [19]:
@code_native f(5,6)

	.text
	.file	"f"
	.globl	julia_f_2501                    # -- Begin function julia_f_2501
	.p2align	4, 0x90
	.type	julia_f_2501,@function
julia_f_2501:                           # @julia_f_2501
; ┌ @ In[11]:5 within `f`
	.cfi_startproc
# %bb.0:                                # %top
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
; │┌ @ int.jl:87 within `+`
	leaq	(%rcx,%rdx), %rax
; │└
	popq	%rbp
	retq
.Lfunc_end0:
	.size	julia_f_2501, .Lfunc_end0-julia_f_2501
	.cfi_endproc
; └
                                        # -- End function
	.section	".note.GNU-stack","",@progbits


In [20]:
@code_native f(5.1,6)

	.text
	.file	"f"
	.globl	julia_f_2503                    # -- Begin function julia_f_2503
	.p2align	4, 0x90
	.type	julia_f_2503,@function
julia_f_2503:                           # @julia_f_2503
; ┌ @ In[11]:5 within `f`
	.cfi_startproc
# %bb.0:                                # %top
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset %rbp, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register %rbp
; │┌ @ promotion.jl:388 within `+`
; ││┌ @ promotion.jl:359 within `promote`
; │││┌ @ promotion.jl:336 within `_promote`
; ││││┌ @ number.jl:7 within `convert`
; │││││┌ @ float.jl:146 within `Float64`
	vcvtsi2sd	%rdx, %xmm1, %xmm1
; ││└└└└
; ││ @ promotion.jl:388 within `+` @ float.jl:383
	vaddsd	%xmm0, %xmm1, %xmm0
; │└
	popq	%rbp
	retq
.Lfunc_end0:
	.size	julia_f_2503, .Lfunc_end0-julia_f_2503
	.cfi_endproc
; └
                                        # -- End function
	.section	".note.GNU-stack","",@progbits


In [21]:
v = [1,2,3,4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [23]:
v3 = [ 3x for x in 1:9] # Python range(1,10), in Julia both elements are inclusive, that's why 9 instead of 10
# note we don't have to use * when multiplying

9-element Vector{Int64}:
  3
  6
  9
 12
 15
 18
 21
 24
 27

In [25]:
v3[1:4] # it shows elements from 1 to 4

4-element Vector{Int64}:
  3
  6
  9
 12

In [26]:
v₄= [ √x₁ for x₁ in 1:9]  # square root done by \sqrt

9-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0

In [27]:
typeof(v3)

Vector{Int64} (alias for Array{Int64, 1})

In [30]:
typeof(v4)

LoadError: UndefVarError: v4 not defined

In [29]:
typeof(v₄)

Vector{Float64} (alias for Array{Float64, 1})

In [31]:
eltype(v3)

Int64

In [32]:
eltype(v₄)

Float64

In [37]:
b = Int[]

Int64[]

In [35]:
Float64[]

Float64[]

In [34]:
c = [] # it's bad ! it is better to declare types like above

Any[]

In [38]:
c = Complex(1,4)

1 + 4im

In [39]:
typeof(c)

Complex{Int64}

In [40]:
dump(c) # to see how c is stored

Complex{Int64}
  re: Int64 1
  im: Int64 4


In [41]:
c2=Complex{Float64}(1,4)

1.0 + 4.0im

In [42]:
typeof(c2)

ComplexF64 (alias for Complex{Float64})

In [43]:
c2=Complex{Float32}(1,4)
typeof(c2)

ComplexF32 (alias for Complex{Float32})

In [44]:
c3=Complex{Rational{Int128}}(1//4,4)
typeof(c3)

Complex{Rational{Int128}}

In [45]:
x = 1//2 + 1//4

3//4

In [48]:
typeof(x)

Rational{Int64}

In [49]:
y = 1/2 +1/4

0.75

### Data types

In [51]:
parse(Float64, "3.7")

3.7

In [52]:
one(Float64), zero(UInt32) # unsigned int

(1.0, 0x00000000)

In [53]:
# shows the code and what it returns ( i guess)

@show Int64('a') 	# character to integer
@show Int64(2.0) 	# float to integer
#Int64(1.3) 		# inexact error
#Int64("a") 		# error no conversion possible
@show Float64(1) 	# integer to float
@show Bool(1) 		# boolean true
@show Bool(0) 		# boolean false
@show Char(89) 		# integer to char
@show zero(10.0) 	# zero of  arg type (Float64)
@show one(Int64) 	# one of type Int64
@show convert(Int64, 1.0)	# float to integer
@show parse(Int64, "1") 

Int64('a') = 97
Int64(2.0) = 2
Float64(1) = 1.0
Bool(1) = true
Bool(0) = false
Char(89) = 'Y'
zero(10.0) = 0.0
one(Int64) = 1
convert(Int64, 1.0) = 1
parse(Int64, "1") = 1


1

In [ ]:
@show Int <: Any
@show Int <: Union{Int, Float64}
@show typeof(nothing)

In [ ]:
f(x) = println("x= $x ")
res = f(1)
typeof(res)

In [ ]:
π # done by \pi

In [56]:
typeof(π)

Irrational{:π}

In [60]:
setprecision(1000)
@show BigFloat(π)

BigFloat(π) = 3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284756482337867831652712019091456485669234603486104543266482133936072602491412736


3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284756482337867831652712019091456485669234603486104543266482133936072602491412736

### Tuples

In [54]:
@show () 		# empty tuple
@show (1,) 		# one element tuple
@show ("a", 1) 	# two element tuple
@show ('a', false)::Tuple{Char, Bool} # tuple type assertion
@show x = (1, 2, 3)
@show x[1] 		# first element
@show x[1:2] 	# (1, 2) (tuple)
# x[4] 		# bounds error
# x[1] = 1 	# error - tuple is not mutable
@show a, b = x 	# tuple unpacking a==1, b==2


() = ()
(1,) = (1,)
("a", 1) = ("a", 1)
('a', false)::Tuple{Char, Bool} = ('a', false)
x = (1, 2, 3) = (1, 2, 3)
x[1] = 1
x[1:2] = (1, 2)
(a, b) = x = (1, 2, 3)


(1, 2, 3)

In [ ]:
t = (3, 3.0)
typeof(t)

In [ ]:
k = (1, "k",  1//5)
typeof(k)

In [ ]:
v = collect(3:10)
v[7:end]

### Matrices

In [63]:
Array{Char}(undef, 2, 3, 4) 	# 2x3x4 array of Chars
@show Array{Any}(undef, 2, 3) 	# 2x3 array of Any
@show zeros(5) 				# vector of Float64 zeros
@show ones(Int64, 2, 1) 	# 2x1 array of Int64 ones
@show trues(3), falses(3) 	# tuple of vector of trues and of falses

@show x = range(1, stop=2, length=5)  # iterator having 5 equally spaced elements
@show collect(x) 	# converts iterator to vector
@show 1:10 			# iterable from 1 to 10
@show 1:2:10 		# iterable from 1 to 9 with 2 skip
@show reshape(1:12, 3, 4)	# 3x4 array filled with 1:12 values


Array{Any}(undef, 2, 3) = Any[#undef #undef #undef; #undef #undef #undef]
zeros(5) = [0.0, 0.0, 0.0, 0.0, 0.0]
ones(Int64, 2, 1) = [1; 1;;]
(trues(3), falses(3)) = (Bool[1, 1, 1], Bool[0, 0, 0])
x = range(1, stop = 2, length = 5) = 1.0:0.25:2.0
collect(x) = [1.0, 1.25, 1.5, 1.75, 2.0]
1:10 = 1:10
1:2:10 = 1:2:9
reshape(1:12, 3, 4) = [1 4 7 10; 2 5 8 11; 3 6 9 12]


3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [64]:
y = Matrix{Int64}(undef, 2, 3) # matrix has already defined number od dimentions

2×3 Matrix{Int64}:
         0  265847056  265875728
 265875728          0  265847056

In [66]:
Matrix # you can see it has already defined 2 dimentions

Matrix (alias for Array{T, 2} where T)

In [67]:
y = Matrix{Int64}(undef, 2, 3) # it already has some numers because of its placement in the memory

2×3 Matrix{Int64}:
 231062016  231062240  156107568
 231062032  156108272  156107696

In [68]:
m = zeros( 4,5)
m[1,3] = 66
m
# 1-based numbering 

4×5 Matrix{Float64}:
 0.0  0.0  66.0  0.0  0.0
 0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0  0.0

In [69]:
m1 = zeros( Int8, 4,5)
m1[1,3] = 66
m1

4×5 Matrix{Int8}:
 0  0  66  0  0
 0  0   0  0  0
 0  0   0  0  0
 0  0   0  0  0

In [70]:
m[:,3] #array slicing

4-element Vector{Int8}:
 66
  0
  0
  0

In [71]:
a = reshape(1:12, 3, 4)


3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [72]:
a1 = collect(reshape(1:12, 3, 4)) # this way we turn it into matrix


3×4 Matrix{Int64}:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [73]:
a = reshape(1:12_000_000_000, 3_000, 4_000_000) # if we did something this huge on the matrix type, we would
# run out of RAM; with reshape computer does not burn


3000×4000000 reshape(::UnitRange{Int64}, 3000, 4000000) with eltype Int64:
    1  3001  6001   9001  12001  15001  18001  …  11999994001  11999997001
    2  3002  6002   9002  12002  15002  18002     11999994002  11999997002
    3  3003  6003   9003  12003  15003  18003     11999994003  11999997003
    4  3004  6004   9004  12004  15004  18004     11999994004  11999997004
    5  3005  6005   9005  12005  15005  18005     11999994005  11999997005
    6  3006  6006   9006  12006  15006  18006  …  11999994006  11999997006
    7  3007  6007   9007  12007  15007  18007     11999994007  11999997007
    8  3008  6008   9008  12008  15008  18008     11999994008  11999997008
    9  3009  6009   9009  12009  15009  18009     11999994009  11999997009
   10  3010  6010   9010  12010  15010  18010     11999994010  11999997010
   11  3011  6011   9011  12011  15011  18011  …  11999994011  11999997011
   12  3012  6012   9012  12012  15012  18012     11999994012  11999997012
   13  3013  6013   9013 

In [74]:
a = reshape(1:12, 3, 4)
display(a[:, 3:end]) # 3x2 matrix
display(a[:, 1]) # 3 element vector
display(a[1, :]) # 4 element vector


3×2 Matrix{Int64}:
 7  10
 8  11
 9  12

3-element Vector{Int64}:
 1
 2
 3

4-element Vector{Int64}:
  1
  4
  7
 10

### Data structures

In [76]:
mutable struct Point1
  x::Int 
  y::Float64
  meta # not givin type is equivalent to writing meta::Any ; destroys efficience!
end
p = Point1(0, 0.0, "Origin")
@show p
@show p.x 		# access field
p.meta = 2		# change field value
@show fieldnames(typeof(p)) # get names of instance fields, does not work on p, works on the type of the object
@show fieldnames(Point1); 	# get names of type fields


p = Point1(0, 0.0, "Origin")
p.x = 0
fieldnames(typeof(p)) = (:x, :y, :meta)
fieldnames(Point1) = (:x, :y, :meta)


In [77]:
dump(:x) # colon is somehow connected to symbols

Symbol x


In [78]:
dump(p)

Point1
  x: Int64 0
  y: Float64 0.0
  meta: Int64 2


In [79]:
fieldnames(typeof(p))

(:x, :y, :meta)

In [80]:
dump(:a)

Symbol a


In [81]:
# we can define default values inside structure thanks to macro Base.@kwdef
# makra zmieniają coś w kompilacji, dlatego to działa, rozszerza się składnia języka (or sth like that)

Base.@kwdef struct Point2
  x::Int64 = 1
  y::Float64 = 2.0
  meta
end
p2 = Point2(x=999, meta = "Origin")

Point2(999, 2.0, "Origin")

In [82]:
try 
    p2.x = 33333
catch e
    println(e)
end

# does not work cause here we try to modify immutable structure

ErrorException("setfield!: immutable struct of type Point2 cannot be changed")


In [ ]:
using Parameters
@with_kw mutable struct Point3
  x::Int64 = 1
  y::Float64 = 2.0
  meta
end
p3 = Point3(x=999, meta = "Origin")
p3.x = 66
p3

In [ ]:
Point3(;x=11,meta="ss")

### Dictionaries

In [83]:
x = Dict{Int, Float64}() 
x[5] = 66.6
x[7] = 99

x

Dict{Int64, Float64} with 2 entries:
  5 => 66.6
  7 => 99.0

In [84]:
x2 = Dict{Any, Any}() 
x2[5] = 66.6
x2[7] = 99

x2

Dict{Any, Any} with 2 entries:
  5 => 66.6
  7 => 99

In [85]:
1=>5

1 => 5

In [86]:
typeof(1=>5)

Pair{Int64, Int64}

In [87]:
y = Dict(1=>5.5, 2=>4.5) 

Dict{Int64, Float64} with 2 entries:
  2 => 4.5
  1 => 5.5

In [88]:
x = Dict{Int, Float64}() # empty dictionary mapping integers to floats
y = Dict(1=>5.5, 2=>4.5) 	# created dictionary
@show y[2] 					# get element
@show y[3] = 30.0 			# add element
@show haskey(y, 2) 			# check if key exists
@show keys(y), values(y) # iterators returning dictionary keys and values
@show delete!(y, 2)   # removing elements see also: pop!
@show get(y, 2, 777) # returns y[2] or 777 if not haskey(y,2)


y[2] = 4.5
y[3] = 30.0 = 30.0
haskey(y, 2) = true
(keys(y), values(y)) = ([2, 3, 1], [4.5, 30.0, 5.5])
delete!(y, 2) = Dict(3 => 30.0, 1 => 5.5)
get(y, 2, 777) = 777


777

### Text processing

In [89]:
@show "Hi " * "there!" 		# concatenation
@show "Ho " ^ 3 			# multiplication
@show string("a= ", 123.3) 	# joining elements to text
@show occursin("CD","ABCD") 	# occurence
@show "\"\n\t\$" # C-like escaping, additionally escape \$ 
                          # escaping - similiar to Matlab, Python, R
x = 123
@show "$x + 3 = $(x+3)"  # $ is an interpolation operator
@show "\$199" # that is why you need escaping

r = r"A|B" # full support for regular expressions
@show occursin(r, "CD") # false, not found
@show m = match(r, "ACBD"); # first regexp match 


"Hi " * "there!" = "Hi there!"
"Ho " ^ 3 = "Ho Ho Ho "
string("a= ", 123.3) = "a= 123.3"
occursin("CD", "ABCD") = true
"\"\n\t\$" = "\"\n\t\$"
"$(x) + 3 = $(x + 3)" = "123 + 3 = 126"
"\$199" = "\$199"
occursin(r, "CD") = false
m = match(r, "ACBD") = RegexMatch("A")


In [90]:
# very convienient!
x = 123
@show "$x + 3 = $(x+3)"  # $ is an interpolation operator

"$(x) + 3 = $(x + 3)" = "123 + 3 = 126"


"123 + 3 = 126"

In [ ]:

x = 6

tekst = "hello $x and $(x*x+2x)"

In [ ]:
str = raw"c:\windows\n"

In [ ]:
?@raw_str

### Functions

In [92]:
f(x, y = 10) = x + y 
# for this function the default value of y is 10
@show f(3, 2) # 5 is returned
@show f(3)    # 13 is returned



f(3, 2) = 5
f(3) = 13


13

In [95]:
function g(x::Int, y::Int) # limit arg type
    return y, x # tuple returned 
  end
  
g(x::Int, y::Bool) = x * y # multiple dispatch
g(x, y) = x - y

methods(g)

# 3 methods for generic function "g":
[1] g(x::Int64, y::Int64) in Main at In[95]:1
[2] g(x::Int64, y::Bool) in Main at In[95]:4
[3] g(x, y) in Main at In[95]:5

In [96]:
@show g(2, true) # 2nd definition will be called
@show methods(g); # list of methods for g

g(2, true) = 2
methods(g) = # 3 methods for generic function "g":
[1] g(x::Int64, y::Int64) in Main at In[95]:1
[2] g(x::Int64, y::Bool) in Main at In[95]:4
[3] g(x, y) in Main at In[95]:5


In [ ]:
function g(x::Int, y::Int) # limit arg type
  return y, x # tuple returned 
end

g(x::Int, y::Bool) = x * y # multiple dispatch

@show g(1,2)
@show g(1, true)


In [ ]:
methods(g)

In [ ]:
@show g(1,4)
@show g(1,true)
methods(g)

### Operators

In [99]:
[1 2] .< [2 1] #shows 1 for true, 2 for false

1×2 BitMatrix:
 1  0

In [97]:
@show true || false # binary or operator (singeltons only)
@show 1 < 2 < 3     # condition chaining  is OK 
@show [1 2] .< [2 1] # vectorization via dot operator "."
@show a = 5
@show 2a + 2(a+1) # multiplication can be ommited 
@show x = [1 2 3]	  #matrix 1×3 Array{Int64,2}    
@show y = [1, 2, 3]  #matrix 3-elements Array{Int64,1}
# vectors are vecticar and are different concept than horizontal 1-row matrix
#x + y # error
@show x .+ y # 3x3 matrix, dimension broadcasting
@show x + y' # 1x3 matrix
@show x * y; # array multiplication, 1-element vector (not scalar)


true || false = true
1 < 2 < 3 = true
[1 2] .< [2 1] = Bool[1 0]
a = 5 = 5
2a + 2 * (a + 1) = 22
x = [1 2 3] = [1 2 3]
y = [1, 2, 3] = [1, 2, 3]
x .+ y = [2 3 4; 3 4 5; 4 5 6]
x + y' = [2 4 6]
x * y = [14]


1-element Vector{Int64}:
 14

In [ ]:
f(x,y) =  x<y ? x : y

In [ ]:
f(10,30)

In [ ]:
a=  [1,2,3]
b=  [0,5,6]

In [ ]:
f.(a,b)

In [ ]:
a .* b

### Simple demo

In [100]:
function calc_pi(n, T)
    # n is the number of replications
    # T is the result type
    s = one(T)
    f = one(T)
    for i::T in 1:n
        f *= i/(2i+1)
        s += f
    end
    2s
end

calc_pi (generic function with 1 method)

In [ ]:
π
typeof(π)

In [ ]:
π

In [ ]:
for T in [Float16, Float64, BigFloat]
    display([calc_pi(2^n, T) for n in 1:10] .- big(π))
end

In [101]:
calc_pi(10000, BigFloat)- π


3.73305447401287551596035817889526867846836578548683209848685735918386764390310253781776130839152440943837995972129697049686195008541612957936608326881572302493764266455330060109598030394360732604440196318506045247296205005918373516322071308450166041524279351541770592447787925691464383688807065164177119e-301

In [ ]:
setprecision(1000) do
    calc_pi(1000, BigFloat)-π
end

In [ ]:
setprecision(8000) do
    @show BigFloat(π)
    end;

In [102]:
[calc_pi(n, Rational) for n in 1:20]

20-element Vector{Rational{Int64}}:
                8//3
               44//15
               64//21
              976//315
            10816//3465
           141088//45045
            47104//15015
          2404096//765765
         45693952//14549535
         45701632//14549535
         80863232//25741485
       5256312832//1673196525
       3153846272//1003917915
     457311809536//145568097675
     833925152768//265447707525
    4725585805312//1504203675975
   14176771899392//4512611027925
  524540820979712//166966608033225
  104908189597696//33393321606645
 4301236281540608//1369126185872445

### Integration with other programming languages

In [ ]:
using PyCall
np = pyimport("numpy")



In [ ]:
a = np.zeros((4, 5), dtype="int32")
a

In [ ]:
a[1,1]=5
np.mean(a)

In [ ]:
b = py"{ (x,y):x*y for x in range(1,5) for y in range(1,3) }"
b

In [ ]:
using Distributions, DataFrames, Random
Random.seed!(0);
dat = permutedims(rand(MvNormal([1 0.75; 0.75 1]), 1000))
df = DataFrame(dat, :auto)


You need to have RCall for this demo together with R present in the operating system, hence this will be shown by the instructor only. 
However you could try installing it yourself:
```
using Pkg
pkg"add RCall"
```

In [ ]:
try
    using RCall
    @rlibrary ggplot2
    ggplot(df,aes(x=:x1,y=:x2)) + geom_point()
catch e; end

In [ ]:
try
    using RCall
    R"library(ggplot2)"
    R"ggplot($df,aes(x=x1,y=x2)) + geom_point()"
catch e; end

*Preparation of this workshop has been supported by the Polish National Agency for Academic Exchange under the Strategic Partnerships programme, grant number BPI/PST/2021/1/00069/U/00001.*

![SGH & NAWA](logo.png)